### ISSUE TITLE
assert result.hostname is not None

### ISSUE THREAD

**Issue by YCA-eng** [baaivision/EVA#39]
Thanks for your excellent work！
When I use --num-gpus=2, I get the following error, I can't solve the problem, and I hope to get your help.

Traceback (most recent call last):
  File "tools/lazyconfig_train_net.py", line 125, in <module>
    launch(
  File "/public/home/1/code/EVA/det/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
**torch.multiprocessing.spawn.ProcessRaisedException:** 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/public/home/1/code/EVA/det/detectron2/engine/launch.py", line 108, in _distributed_worker
    raise e
  File "/public/home/1/code/EVA/det/detectron2/engine/launch.py", line 98, in _distributed_worker
    dist.init_process_group(
  File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 141, in _tcp_rendezvous_handler
    **assert result.hostname is not None
AssertionError**

This is my running code：
   python tools/lazyconfig_train_net.py --num-gpus 2 \
    --num-machines 1 --machine-rank 0 --dist-url "tcp://$MASTER_ADDR:60900" \
     --config-file projects/ViTDet/configs/COCO/cascade_mask_rcnn_vitdet_eva.py \

**Comment by YCA-eng** [comment]
> Thanks for your excellent work！ When I use --num-gpus=2, I get the following error, I can't solve the problem, and I hope to get your help.
> 
> Traceback (most recent call last): File "tools/lazyconfig_train_net.py", line 125, in launch( File "/public/home/1/code/EVA/det/detectron2/engine/launch.py", line 67, in launch mp.spawn( File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn return start_processes(fn, args, nprocs, join, daemon, start_method='spawn') File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes while not context.join(): File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join raise ProcessRaisedException(msg, error_index, failed_process.pid) **torch.multiprocessing.spawn.ProcessRaisedException:**
> 
> -- Process 0 terminated with the following error: Traceback (most recent call last): File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap fn(i, *args) File "/public/home/1/code/EVA/det/detectron2/engine/launch.py", line 108, in _distributed_worker raise e File "/public/home/1/code/EVA/det/detectron2/engine/launch.py", line 98, in _distributed_worker dist.init_process_group( File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group store, rank, world_size = next(rendezvous_iterator) File "/public/home/1/Anaconda3/envs/EVA/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 141, in _tcp_rendezvous_handler **assert result.hostname is not None AssertionError**
> 
> This is my running code： python tools/lazyconfig_train_net.py --num-gpus 2 --num-machines 1 --machine-rank 0 --dist-url "tcp://$MASTER_ADDR:60900" --config-file projects/ViTDet/configs/COCO/cascade_mask_rcnn_vitdet_eva.py \

tcp://127.0.0.1:8686
